### ISSUE TITLE
Koishi 无法连后端。

### ISSUE THREAD

**Issue by lychees** [MirrorCY/openchat#4]
参考了[视频教程](https://www.bilibili.com/video/BV1PT41197AK/)。
后端起来了，本地可以 ping 通。

但 Koishi 方面 ask 后秒返回：网络异常或服务器关闭。
后端方面没有收到消息。

**Comment by fuzhuovo** [comment]
> 参考了[视频教程](https://www.bilibili.com/video/BV1PT41197AK/)。 后端起来了，本地可以 ping 通。
> 
> 但 Koishi 方面 ask 后秒返回：网络异常或服务器关闭。 后端方面没有收到消息。

看看后端的日志呢

**Comment by MirrorCY** [comment]
我忘记这个问题解决没了，好像是设置了全局代理导致 Koishi 的请求并未发到后端
后端没有日志

**Comment by MirrorCY** [comment]
我记得在群里帮你解决了，你看下是否要关闭此 issue，还是我记错人了
