### ISSUE TITLE
【请求优化】返回的结果不能正确显示换行

### ISSUE THREAD

**Issue by rainpenber** [MirrorCY/openchat#5]
在qq里的返回结果换行应该是 
``` text
&#10;
```
本bot的返回值效果：
![Snipaste_2023-03-09_01-59-30](https://user-images.githubusercontent.com/15974476/223792905-00aac53e-92c5-4fbe-93f9-996a054c7075.png)
附：其他bot的正确显示效果：
![Snipaste_2023-03-09_01-58-40](https://user-images.githubusercontent.com/15974476/223792758-17fa2014-3f7f-4a52-911e-a67759aee9bc.png)

**Comment by MirrorCY** [comment]
确认目前返回的所有换行都消失了吗，插件是按原样将消息送至 Koishi 的

**Comment by MirrorCY** [comment]
试试重置会话再发送几次

**Comment by rainpenber** [comment]
@MirrorCY 
使用的是`chat_gpt-3.5-turbo.py`，也就是填写apikey的方式，这个会有问题吗？
以下是我配置和启动的方式，以及请教一下如何重置会话，是在网页上吗？
```shell
python -m venv chatgpt_venv

cd .\chatgpt-venv\Scripts

.\Activate.ps1

cd ../../

pip3 install -r requirements.txt

python ./chat_gpt-3.5-turbo.py
```
![Snipaste_2023-03-09_02-21-39](https://user-images.githubusercontent.com/15974476/223799584-5a55a2c7-d28d-4d1d-9594-320d18b53027.png)

![Snipaste_2023-03-09_02-21-02](https://user-images.githubusercontent.com/15974476/223799205-ff6e8dbb-3ef6-4606-b7a0-8f9730f9af61.png)

**Comment by MirrorCY** [comment]
这个是另一位小伙伴 pr 上来的，抱歉我合并前并未测试，理论上不应该出现格式问题，你可以向他确认更多信息。
cc @yi03

**Comment by yi03** [comment]
哦不好意思我写错了，等我今晚改吧。

**Comment by yi03** [comment]
试了一下把[这里](https://github.com/MirrorCY/openchat/blob/2d07c2c6b3fe4522b0f9e8d0ed5fe393f68fe02a/chat_gpt-3.5-turbo.py#L25)改成下边这样就行。我fork的仓库已经被我改成openchat2了，不能fork新的了，你来改吧。 @MirrorCY 
```
async def get_text(prompt):
    return chatbot.ask(prompt)
```

**Comment by MirrorCY** [comment]
发你权限了~
你可以直接开分支辣

**Comment by yi03** [comment]
> 发你权限了~ 你可以直接开分支辣

非常抱歉。脑子抽了。总之做了蠢事。其中之一是已经push到main分支了。

**Comment by MirrorCY** [comment]
哈哈哈没事~
确认修复后可以自行关闭此 issue，顺便 openchat2 体验更好哦~
@rainpenber

**Comment by rainpenber** [comment]
@yi03 @MirrorCY 非常感谢，已经修好！感谢作者光速修复 🙏🙏
